// Mock data for development - will be replaced with API calls
import { Item, Borrowing } from "@/types";

export const mockItems: Item[] = [
  {
    id: 1,
    kode_barang: "BRG-001",
    nama_barang: "Tang Crimping RJ45",
  kode_jenis: "TKJ-LTRR",
    status: "Tersedia",
    jumlah_stok: 10,
    jumlah_dipinjam: 3,
    foto_barang: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=400",
    notes: "Untuk crimping kabel UTP",
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    kode_barang: "BRG-002",
    nama_barang: "Kabel Tester",
  kode_jenis: "TKJ-LTRR",
    status: "Tersedia",
    jumlah_stok: 8,
    jumlah_dipinjam: 2,
    foto_barang: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
    notes: "Untuk testing koneksi kabel",
    created_at: new Date().toISOString(),
  },
  {
    id: 3,
    kode_barang: "BRG-003",
    nama_barang: "Obeng Set",
  kode_jenis: "TKJ-LTRR",
    status: "Tersedia",
    jumlah_stok: 15,
    jumlah_dipinjam: 5,
    foto_barang: "https://images.unsplash.com/photo-1530124566582-a618bc2615dc?w=400",
    notes: "Set obeng lengkap",
    created_at: new Date().toISOString(),
  },
  {
    id: 4,
    kode_barang: "BRG-004",
    nama_barang: "LAN Tester",
  kode_jenis: "TKJ-LTRR",
    status: "Dipinjam",
    jumlah_stok: 6,
    jumlah_dipinjam: 1,
    foto_barang: "https://images.unsplash.com/photo-1598986646512-9330bcc4c0dc?w=400",
    notes: "Untuk testing koneksi LAN",
    created_at: new Date().toISOString(),
  },
  {
    id: 5,
    kode_barang: "BRG-005",
    nama_barang: "Kabel UTP Cat6 (Roll)",
  kode_jenis: "TKJ-CABL",
    status: "Dipinjam",
    jumlah_stok: 20,
    jumlah_dipinjam: 8,
    foto_barang: "https://images.unsplash.com/photo-1551818014-7c8ace9c3084?w=400",
    notes: "Kabel UTP Category 6",
    created_at: new Date().toISOString(),
  },
  {
    id: 6,
    kode_barang: "BRG-006",
    nama_barang: "RJ45 Connector (Box)",
  kode_jenis: "TKJ-CONN",
    status: "Tersedia",
    jumlah_stok: 50,
    jumlah_dipinjam: 15,
    foto_barang: "https://images.unsplash.com/photo-1597852074816-d933c7d2b988?w=400",
    notes: "Konektor RJ45 untuk kabel UTP",
    created_at: new Date().toISOString(),
  },
];

export const mockBorrowings: Borrowing[] = [
  {
    id: 1,
    kode_peminjaman: "PMJ-2025-001",
    id_barang: 1,
    nama_peminjam: "Ahmad Fauzi",
    kontak: "081234567890",
    keperluan: "Praktikum Jaringan Komputer",
    guru_pendamping: "Pak Budi",
    jumlah: 2,
    foto_credential: "https://images.unsplash.com/photo-1633332755192-727a05c4013d?w=400",
    tanggal_pinjam: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    tanggal_kembali: undefined,
    status: 'Dipinjam',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    nama_barang: "Tang Crimping RJ45",
  },
  {
    id: 2,
    kode_peminjaman: "PMJ-2025-002",
    id_barang: 3,
    nama_peminjam: "Siti Nurhaliza",
    kontak: "082345678901",
    keperluan: "Maintenance Lab Komputer",
    guru_pendamping: "Bu Ani",
    jumlah: 1,
    foto_credential: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400",
    tanggal_pinjam: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    tanggal_kembali: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'Dikembalikan',
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    nama_barang: "Obeng Set",
  },
  // Today's borrowings
  {
    id: 3,
    kode_peminjaman: "PMJ-2025-003",
    id_barang: 2,
    nama_peminjam: "Rini Sutrisno",
    kontak: "083456789012",
    keperluan: "Praktikum Kabel Jaringan",
    guru_pendamping: "Pak Dino",
    jumlah: 3,
    foto_credential: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    tanggal_pinjam: new Date().toISOString(),
    tanggal_kembali: undefined,
    status: 'Dipinjam',
    created_at: new Date().toISOString(),
    nama_barang: "Kabel Tester",
  },
  {
    id: 4,
    kode_peminjaman: "PMJ-2025-004",
    id_barang: 4,
    nama_peminjam: "Ari Wibowo",
    kontak: "084567890123",
    keperluan: "Troubleshooting Jaringan",
    guru_pendamping: "Bu Sita",
    jumlah: 1,
    foto_credential: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400",
    tanggal_pinjam: new Date().toISOString(),
    tanggal_kembali: undefined,
    status: 'Dipinjam',
    created_at: new Date().toISOString(),
    nama_barang: "LAN Tester",
  },
  {
    id: 5,
    kode_peminjaman: "PMJ-2025-005",
    id_barang: 5,
    nama_peminjam: "Dewi Lestari",
    kontak: "085678901234",
    keperluan: "Instalasi Kabel",
    guru_pendamping: "Pak Budi",
    jumlah: 2,
    foto_credential: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400",
    tanggal_pinjam: new Date().toISOString(),
    tanggal_kembali: undefined,
    status: 'Dipinjam',
    created_at: new Date().toISOString(),
    nama_barang: "Kabel UTP Cat6 (Roll)",
  },
  // This month borrowings
  {
    id: 6,
    kode_peminjaman: "PMJ-2025-006",
    id_barang: 6,
    nama_peminjam: "Budi Santoso",
    kontak: "086789012345",
    keperluan: "Lab Praktikum",
    guru_pendamping: "Bu Ani",
    jumlah: 5,
    foto_credential: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    tanggal_pinjam: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    tanggal_kembali: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'Dikembalikan',
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    nama_barang: "RJ45 Connector (Box)",
  },
  {
    id: 7,
    kode_peminjaman: "PMJ-2025-007",
    id_barang: 1,
    nama_peminjam: "Toni Hermawan",
    kontak: "087890123456",
    keperluan: "Praktikum Lab TKJ",
    guru_pendamping: "Pak Dino",
    jumlah: 1,
    foto_credential: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400",
    tanggal_pinjam: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    tanggal_kembali: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'Dikembalikan',
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    nama_barang: "Tang Crimping RJ45",
  },
];

// Detail peminjaman (fallback for admin views)
export const mockDetailPeminjaman = [
  { peminjaman_id: 1, id_barang: 1, kode_barang: "BRG-001", nama_barang: "Tang Crimping RJ45", jumlah: 2 },
  { peminjaman_id: 2, id_barang: 3, kode_barang: "BRG-003", nama_barang: "Obeng Set", jumlah: 1 },
  { peminjaman_id: 3, id_barang: 2, kode_barang: "BRG-002", nama_barang: "Kabel Tester", jumlah: 2 },
  { peminjaman_id: 3, id_barang: 5, kode_barang: "BRG-005", nama_barang: "Kabel UTP Cat6 (Roll)", jumlah: 1 },
  { peminjaman_id: 4, id_barang: 4, kode_barang: "BRG-004", nama_barang: "LAN Tester", jumlah: 1 },
  { peminjaman_id: 5, id_barang: 5, kode_barang: "BRG-005", nama_barang: "Kabel UTP Cat6 (Roll)", jumlah: 2 },
  { peminjaman_id: 6, id_barang: 6, kode_barang: "BRG-006", nama_barang: "RJ45 Connector (Box)", jumlah: 5 },
  { peminjaman_id: 7, id_barang: 1, kode_barang: "BRG-001", nama_barang: "Tang Crimping RJ45", jumlah: 1 },
];

// Extended borrowing data with student/teacher info for admin display
export const mockBorrowingsExtended = [
  {
    id: 1,
    kode_peminjaman: "PMJ-2025-001",
    nama_peminjam: "Ahmad Fauzi",
    nip_nis: "14301/2364.066",
    kontak: "081234567890",
    foto_credential: "https://images.unsplash.com/photo-1633332755192-727a05c4013d?w=400",
    tipe_peminjam: "siswa",
    guru_pendamping: "Pak Budi Santoso",
    keperluan: "Praktikum Jaringan Komputer",
    tanggal_pinjam: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    tanggal_kembali: undefined,
    status: "Dipinjam",
    detail_ids: [1],
  },
  {
    id: 2,
    kode_peminjaman: "PMJ-2025-002",
    nama_peminjam: "Siti Nurhaliza",
    nip_nis: "14302/2365.066",
    kontak: "082345678901",
    foto_credential: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400",
    tipe_peminjam: "siswa",
    guru_pendamping: "Bu Ani Wijaya",
    keperluan: "Maintenance Lab Komputer",
    tanggal_pinjam: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    tanggal_kembali: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    status: "Dikembalikan",
    detail_ids: [2],
  },
  {
    id: 3,
    kode_peminjaman: "PMJ-2025-003",
    nama_peminjam: "Rini Sutrisno",
    nip_nis: "14304/2367.066",
    kontak: "083456789012",
    foto_credential: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    tipe_peminjam: "siswa",
    guru_pendamping: "Pak Dino Pratama",
    keperluan: "Praktikum Kabel Jaringan",
    tanggal_pinjam: new Date().toISOString(),
    tanggal_kembali: undefined,
    status: "Dipinjam",
    detail_ids: [3, 4],
  },
  {
    id: 4,
    kode_peminjaman: "PMJ-2025-004",
    nama_peminjam: "Ari Wibowo",
    nip_nis: "14305/2368.066",
    kontak: "084567890123",
    foto_credential: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400",
    tipe_peminjam: "siswa",
    guru_pendamping: "Bu Sita Rahman",
    keperluan: "Troubleshooting Jaringan",
    tanggal_pinjam: new Date().toISOString(),
    tanggal_kembali: undefined,
    status: "Dipinjam",
    detail_ids: [4],
  },
  {
    id: 5,
    kode_peminjaman: "PMJ-2025-005",
    nama_peminjam: "Dewi Lestari",
    nip_nis: "14309/2372.066",
    kontak: "085678901234",
    foto_credential: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400",
    tipe_peminjam: "siswa",
    guru_pendamping: "Pak Budi Santoso",
    keperluan: "Instalasi Kabel",
    tanggal_pinjam: new Date().toISOString(),
    tanggal_kembali: undefined,
    status: "Dipinjam",
    detail_ids: [5],
  },
  {
    id: 6,
    kode_peminjaman: "PMJ-2025-006",
    nama_peminjam: "Budi Santoso",
    nip_nis: "NIP-001",
    kontak: "086789012345",
    foto_credential: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    tipe_peminjam: "guru",
    guru_pendamping: null,
    keperluan: "Lab Praktikum",
    tanggal_pinjam: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    tanggal_kembali: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    status: "Dikembalikan",
    detail_ids: [6],
  },
  {
    id: 7,
    kode_peminjaman: "PMJ-2025-007",
    nama_peminjam: "Toni Hermawan",
    nip_nis: "14317/2380.066",
    kontak: "087890123456",
    foto_credential: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400",
    tipe_peminjam: "siswa",
    guru_pendamping: "Pak Dino Pratama",
    keperluan: "Praktikum Lab TKJ",
    tanggal_pinjam: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    tanggal_kembali: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    status: "Dikembalikan",
    detail_ids: [7],
  },
];

// Available classes
export const kelasOptions = ["X TKJ 1", "X TKJ 2", "X TKJ 3", "XI TKJ 1", "XI TKJ 2", "XI TKJ 3"];

// Generate 100 mock teachers
const teacherFirstNames = [
  "Andi", "Budi", "Citra", "Dedi", "Eka", "Feri", "Gita", "Hendra", "Ira", "Joko",
  "Karin", "Lina", "Mitra", "Nanda", "Oka", "Putri", "Qintar", "Rindi", "Susi", "Tika",
  "Udin", "Vina", "Wawan", "Xander", "Yudi", "Zara", "Agus", "Bella", "Cerita", "Dadan",
  "Eka", "Fahmi", "Gina", "Hafis", "Inti", "Joko", "Kiki", "Livia", "Meri", "Novi",
  "Ocha", "Peni", "Qonita", "Rani", "Sigit", "Tania", "Ulfa", "Vega", "Winda", "Xenia",
  "Yasir", "Zahra", "Alvaro", "Bambang", "Ceria", "Dani", "Elisa", "Fajar", "Gilang", "Hani",
  "Irwan", "Josua", "Karma", "Lena", "Marno", "Nandi", "Osman", "Purno", "Querino", "Rian",
  "Sandi", "Tino", "Ulfah", "Vital", "Widia", "Xenia", "Yolanda", "Zikri", "Abdur", "Binar",
  "Castor", "Danang", "Elmo", "Fanda", "Gading", "Hafiz", "Ilyas", "Jarwo", "Karim", "Liang"
];

const teacherLastNames = [
  "Bayu", "Santoso", "Wijaya", "Kusuma", "Suharto", "Hartono", "Gunawan", "Pratama", "Rahman", "Ibrahim",
  "Setya", "Prabowo", "Suryanto", "Budiman", "Ardhana", "Rosmalina", "Handoko", "Setiawan", "Mahendra", "Wijaksono",
  "Handoyo", "Sutrisno", "Hapsara", "Mulyadi", "Supriyanto", "Wardhana", "Kusnandar", "Subagyo", "Wijaya", "Rismanto"
];

export const mockTeachers = Array.from({ length: 100 }, (_, i) => ({
  name: `${teacherFirstNames[i % teacherFirstNames.length]} ${teacherLastNames[i % teacherLastNames.length]}`,
  nip: `NIP-${String(i + 1).padStart(3, "0")}`,
}));

// Mock students with kelas data - organized by class
const studentDataByClass = {
  "X TKJ 1": [
    { name: "ABDULLOH ARRAFIFF", nis: "14301/2364.066" },
    { name: "ABY NUR SYAHDANI", nis: "14302/2365.066" },
    { name: "ADAM PRANANDA SUHENDAR", nis: "14304/2367.066" },
    { name: "ADEVITA INDRIYANTI", nis: "14305/2368.066" },
    { name: "AHMAD MAFTUHUR RIZQY", nis: "14309/2372.066" },
    { name: "AMELDA FITRI AYU PERMATA", nis: "14317/2380.066" },
    { name: "BENY WAHYUDI AKBAR", nis: "14326/2389.066" },
    { name: "CHARLY ANANDA PUTRA AFANDI", nis: "14329/2392.066" },
    { name: "CINTA AFIDAHTUL ISMA AINI", nis: "14330/2393.066" },
    { name: "FADHIL MAULANA PRATAMA", nis: "14339/2402.066" },
    { name: "FATIMAH", nis: "14341/2404.066" },
    { name: "FINO SEPTIAN AFANDI", nis: "14343/2406.066" },
    { name: "HILMIY FAKHRY AL FARIZI", nis: "14345/2408.066" },
    { name: "IBRAHIM SALIM SYAKIF", nis: "14346/2409.066" },
    { name: "INGE PANDALUWANGSA", nis: "14347/2410.066" },
    { name: "KEVIN WIDDAD BRAMANTYO", nis: "14349/2412.066" },
    { name: "MASHI ARDIKA", nis: "14357/2420.066" },
    { name: "MAULIDHA LAILATUL ZANNA", nis: "14358/2421.066" },
    { name: "MAYLA DIVA SEVILYA", nis: "14359/2422.066" },
    { name: "MEGA RIZKY WIDIYANTO", nis: "14360/2423.066" },
    { name: "MOCH FADIL MAULIDIANSYAH", nis: "14361/2424.066" },
    { name: "MOCHAMMAD JUNINHO PRATAMA", nis: "14364/2427.066" },
    { name: "MUHAMAD MARCELINO SYAHPUTRA", nis: "14367/2430.066" },
    { name: "MUHAMMAD RAFAEL DANANG PRIYONO", nis: "14376/2439.066" },
    { name: "MUHAMMAD SATRIA PUTRA PRATAMA", nis: "14379/2442.066" },
    { name: "OKTAVIAN AVIS SHOLEH", nis: "14382/2445.066" },
    { name: "RAFA SHOKHIBUL BAKHRI", nis: "14383/2446.066" },
  ],
  "X TKJ 2": Array.from({ length: 25 }, (_, i) => ({
    name: `Tali Goci ${String(i + 1).padStart(2, "0")}`,
    nis: `14400/2500.06${String(i).padStart(1, "0")}`,
  })),
  "X TKJ 3": Array.from({ length: 25 }, (_, i) => ({
    name: `Jian Ayune ${String(i + 1).padStart(2, "0")}`,
    nis: `14425/2525.06${String(i).padStart(1, "0")}`,
  })),
  "XI TKJ 1": Array.from({ length: 10 }, (_, i) => ({
    name: `Owalah Yowes ${String(i + 1).padStart(2, "0")}`,
    nis: `13700/2350.06${String(i).padStart(1, "0")}`,
  })),
  "XI TKJ 2": Array.from({ length: 10 }, (_, i) => ({
    name: `Yanto Hay ${String(i + 1).padStart(2, "0")}`,
    nis: `13710/2360.06${String(i).padStart(1, "0")}`,
  })),
  "XI TKJ 3": Array.from({ length: 3 }, (_, i) => ({
    name: `ZAHRATUS SADIYAH`,
    nis: `13781/2361.066`,
  })),
};

export const mockStudents = Array.from(
  { length: 100 },
  (_, i) => {
    const klasIndex = Math.floor(i / 20);
    const kelas = kelasOptions[klasIndex] || "X TKJ 1";
    const classStudents = studentDataByClass[kelas] || [];
    const studentIndex = i % Math.max(classStudents.length, 1);
    const student = classStudents[studentIndex] || { name: `Student ${i}`, nis: `NIS-${1001 + i}` };
    return {
      name: student.name,
      nis: student.nis,
      kelas,
    };
  }
);

// Jenis Barang (Tipe Barang)
export const mockJenisBarang = [
  {
    id_jenis_barang: 1,
    kode_jenis_barang: "TKJ-LTRR",
    nama_jenis_barang: "Peralatan Networking",
    deskripsi_jenis_barang: "Peralatan untuk praktik dan maintenance jaringan komputer",
    created_at: new Date().toISOString(),
  },
  {
    id_jenis_barang: 2,
    kode_jenis_barang: "TKJ-CABL",
    nama_jenis_barang: "Kabel & Konektor",
    deskripsi_jenis_barang: "Berbagai jenis kabel networking dan konektor",
    created_at: new Date().toISOString(),
  },
  {
    id_jenis_barang: 3,
    kode_jenis_barang: "TKJ-HARD",
    nama_jenis_barang: "Hardware",
    deskripsi_jenis_barang: "Komponen hardware untuk laboratorium komputer",
    created_at: new Date().toISOString(),
  },
  {
    id_jenis_barang: 4,
    kode_jenis_barang: "TKJ-SOFT",
    nama_jenis_barang: "Software & Lisensi",
    deskripsi_jenis_barang: "Software dan lisensi untuk praktik",
    created_at: new Date().toISOString(),
  },
  {
    id_jenis_barang: 5,
    kode_jenis_barang: "TKJ-BUKU",
    nama_jenis_barang: "Buku & Referensi",
    deskripsi_jenis_barang: "Buku panduan dan referensi teknis",
    created_at: new Date().toISOString(),
  },
  {
    id_jenis_barang: 6,
    kode_jenis_barang: "TKJ-LAIN",
    nama_jenis_barang: "Lainnya",
    deskripsi_jenis_barang: "Barang-barang lain yang tidak masuk kategori",
    created_at: new Date().toISOString(),
  },
];

// Barang (Item per Jenis Barang) - Barang Bengkel TKJ Realistis
export const mockBarang = [
  // Peralatan Networking (TKJ-LTRR)
  {
    id_barang: 1,
    id_jenis_barang: 1,
    kode_barang: "BRG-001",
    nama_barang: "Router Cisco 2911",
    foto_barang: "https://images.unsplash.com/photo-1587829191301-48ca3d11c465?w=400",
    no_serial_number: "CSC-2911-001",
    deskripsi_barang: "Router Cisco untuk routing dan switching jaringan lab",
    status: "Tersedia",
    created_at: new Date().toISOString(),
  },
  {
    id_barang: 2,
    id_jenis_barang: 1,
    kode_barang: "BRG-002",
    nama_barang: "Network Switch 24 Port Cisco",
    foto_barang: "https://images.unsplash.com/photo-1517694712202-14819c9cb5c7?w=400",
    no_serial_number: "CSC-SW24-001",
    deskripsi_barang: "Switch manageable 24 port untuk lab networking",
    status: "Tersedia",
    created_at: new Date().toISOString(),
  },
  {
    id_barang: 3,
    id_jenis_barang: 1,
    kode_barang: "BRG-003",
    nama_barang: "Tang Crimping RJ45 Profesional",
    foto_barang: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=400",
    no_serial_number: "TANG-001",
    deskripsi_barang: "Tang crimping profesional untuk membuat kabel UTP",
    status: "Tersedia",
    created_at: new Date().toISOString(),
  },
  {
    id_barang: 4,
    id_jenis_barang: 1,
    kode_barang: "BRG-004",
    nama_barang: "Cable Tester Digital",
    foto_barang: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
    no_serial_number: "TESTER-001",
    deskripsi_barang: "Alat testing kabel networking dengan display digital",
    status: "Dipinjam",
    created_at: new Date().toISOString(),
  },
  {
    id_barang: 5,
    id_jenis_barang: 1,
    kode_barang: "BRG-005",
    nama_barang: "Multimeter Digital Sanwa",
    foto_barang: "https://images.unsplash.com/photo-1594259534201-8a88fb13ce338?w=400",
    no_serial_number: "SANWA-001",
    deskripsi_barang: "Multimeter untuk pengukuran tegangan, arus, dan resistansi",
    status: "Tersedia",
    created_at: new Date().toISOString(),
  },
  {
    id_barang: 6,
    id_jenis_barang: 1,
    kode_barang: "BRG-006",
    nama_barang: "Obeng Set Presisi 16 Pcs",
    foto_barang: "https://images.unsplash.com/photo-1530124566582-a618bc2615dc?w=400",
    no_serial_number: "OBENG-001",
    deskripsi_barang: "Set obeng presisi lengkap untuk maintenance hardware dan networking",
    status: "Tersedia",
    created_at: new Date().toISOString(),
  },
  // Kabel & Konektor (TKJ-CABL)
  {
    id_barang: 7,
    id_jenis_barang: 2,
    kode_barang: "BRG-007",
    nama_barang: "Kabel UTP Cat6 Roll 100m",
    foto_barang: "https://images.unsplash.com/photo-1551818014-7c8ace9c3084?w=400",
    no_serial_number: "CABLE-100M-001",
    deskripsi_barang: "Kabel UTP Category 6 bersertifikat untuk instalasi jaringan",
    status: "Tersedia",
    created_at: new Date().toISOString(),
  },
  {
    id_barang: 8,
    id_jenis_barang: 2,
    kode_barang: "BRG-008",
    nama_barang: "RJ45 Connector Gold Box 100pcs",
    foto_barang: "https://images.unsplash.com/photo-1597852074816-d933c7d2b988?w=400",
    no_serial_number: "RJ45-BOX-001",
    deskripsi_barang: "Konektor RJ45 berkualitas gold plated dalam box 100 pcs",
    status: "Tersedia",
    created_at: new Date().toISOString(),
  },
  {
    id_barang: 9,
    id_jenis_barang: 2,
    kode_barang: "BRG-009",
    nama_barang: "Kabel Patch UTP Cat5e 2m",
    foto_barang: "https://images.unsplash.com/photo-1606986628025-35d57e735ae0?w=400",
    no_serial_number: "PATCH-2M-001",
    deskripsi_barang: "Kabel patch siap pakai panjang 2 meter untuk koneksi jaringan",
    status: "Dipinjam",
    created_at: new Date().toISOString(),
  },
  {
    id_barang: 10,
    id_jenis_barang: 2,
    kode_barang: "BRG-010",
    nama_barang: "USB to Serial Adapter",
    foto_barang: "https://images.unsplash.com/photo-1597852074816-d933c7d2b988?w=400",
    no_serial_number: "USB-SERIAL-001",
    deskripsi_barang: "Adapter USB to Serial untuk konfigurasi router/switch",
    status: "Tersedia",
    created_at: new Date().toISOString(),
  },
  // Hardware (TKJ-HARD)
  {
    id_barang: 11,
    id_jenis_barang: 3,
    kode_barang: "BRG-011",
    nama_barang: "Oscilloscope Digital Tektronix",
    foto_barang: "https://images.unsplash.com/photo-1517694712202-14819c9cb5c7?w=400",
    no_serial_number: "TEK-SCOPE-001",
    deskripsi_barang: "Oscilloscope 100MHz untuk analisis sinyal jaringan",
    status: "Tersedia",
    created_at: new Date().toISOString(),
  },
  {
    id_barang: 12,
    id_jenis_barang: 3,
    kode_barang: "BRG-012",
    nama_barang: "Protocol Analyzer Wireshark Box",
    foto_barang: "https://images.unsplash.com/photo-1517694712202-14819c9cb5c7?w=400",
    no_serial_number: "PROTO-ANALYZER-001",
    deskripsi_barang: "Hardware protocol analyzer untuk capture dan analisis paket jaringan",
    status: "Tersedia",
    created_at: new Date().toISOString(),
  },
  {
    id_barang: 13,
    id_jenis_barang: 3,
    kode_barang: "BRG-013",
    nama_barang: "Access Point Ubiquiti UniFi",
    foto_barang: "https://images.unsplash.com/photo-1587829191301-48ca3d11c465?w=400",
    no_serial_number: "UBIQ-AP-001",
    deskripsi_barang: "Access point WiFi 5GHz untuk lab wireless",
    status: "Tersedia",
    created_at: new Date().toISOString(),
  },
  {
    id_barang: 14,
    id_jenis_barang: 3,
    kode_barang: "BRG-014",
    nama_barang: "Firewall Mikrotik RB4011",
    foto_barang: "https://images.unsplash.com/photo-1517694712202-14819c9cb5c7?w=400",
    no_serial_number: "MIKTROTIK-FW-001",
    deskripsi_barang: "Firewall dan router Mikrotik untuk lab network security",
    status: "Dipinjam",
    created_at: new Date().toISOString(),
  },
  // Buku & Referensi (TKJ-BUKU)
  {
    id_barang: 15,
    id_jenis_barang: 5,
    kode_barang: "BRG-015",
    nama_barang: "CCNA Routing & Switching Buku",
    foto_barang: "https://images.unsplash.com/photo-1507842217343-583f20270319?w=400",
    no_serial_number: "BOOK-CCNA-001",
    deskripsi_barang: "Buku panduan CCNA untuk routing dan switching",
    status: "Tersedia",
    created_at: new Date().toISOString(),
  },
  {
    id_barang: 16,
    id_jenis_barang: 5,
    kode_barang: "BRG-016",
    nama_barang: "Network Administration Linux",
    foto_barang: "https://images.unsplash.com/photo-1507842217343-583f20270319?w=400",
    no_serial_number: "BOOK-LINUX-001",
    deskripsi_barang: "Buku administrasi jaringan berbasis Linux",
    status: "Tersedia",
    created_at: new Date().toISOString(),
  },
  // Lainnya (TKJ-LAIN)
  {
    id_barang: 17,
    id_jenis_barang: 6,
    kode_barang: "BRG-017",
    nama_barang: "Breadboard 830 Points",
    foto_barang: "https://images.unsplash.com/photo-1595225476933-018acacdb767?w=400",
    no_serial_number: "BREADBOARD-001",
    deskripsi_barang: "Breadboard 830 titik untuk experimenting elektronik",
    status: "Tersedia",
    created_at: new Date().toISOString(),
  },
  {
    id_barang: 18,
    id_jenis_barang: 6,
    kode_barang: "BRG-018",
    nama_barang: "Jumper Wire Set 140pcs",
    foto_barang: "https://images.unsplash.com/photo-1595225476933-018acacdb767?w=400",
    no_serial_number: "JUMPER-SET-001",
    deskripsi_barang: "Set jumper wire 140 pcs untuk breadboard",
    status: "Tersedia",
    created_at: new Date().toISOString(),
  },
];

// Mock data untuk Admin
export const mockAdmins = [
  {
    id: 1,
    username: "admin",
    nama_lengkap: "Administrator TKJ",
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    username: "admin2",
    nama_lengkap: "Admin Backup",
    created_at: new Date().toISOString(),
  },
];

// Mock data untuk Guru
export const mockGuru = [
  { id: 1, nip: "NIP-001", name: "Pak Budi Santoso", created_at: new Date().toISOString() },
  { id: 2, nip: "NIP-002", name: "Bu Ani Wijaya", created_at: new Date().toISOString() },
  { id: 3, nip: "NIP-003", name: "Pak Dino Pratama", created_at: new Date().toISOString() },
  { id: 4, nip: "NIP-004", name: "Bu Sita Rahman", created_at: new Date().toISOString() },
  { id: 5, nip: "NIP-005", name: "Pak Eko Kurniawan", created_at: new Date().toISOString() },
];

// Mock data untuk Siswa
export const mockSiswa = [
  { id: 1, nis: "14301/2364.066", name: "ABDULLOH ARRAFIFF", kelas: "X TKJ 1", created_at: new Date().toISOString() },
  { id: 2, nis: "14302/2365.066", name: "ABY NUR SYAHDANI", kelas: "X TKJ 1", created_at: new Date().toISOString() },
  { id: 3, nis: "14304/2367.066", name: "ADAM PRANANDA SUHENDAR", kelas: "X TKJ 1", created_at: new Date().toISOString() },
  { id: 4, nis: "14305/2368.066", name: "ADEVITA INDRIYANTI", kelas: "X TKJ 1", created_at: new Date().toISOString() },
  { id: 5, nis: "14309/2372.066", name: "AHMAD MAFTUHUR RIZQY", kelas: "X TKJ 1", created_at: new Date().toISOString() },
  { id: 6, nis: "14400/2500.061", name: "Tali Goci 01", kelas: "X TKJ 2", created_at: new Date().toISOString() },
  { id: 7, nis: "14401/2501.061", name: "Tali Goci 02", kelas: "X TKJ 2", created_at: new Date().toISOString() },
  { id: 8, nis: "14425/2525.061", name: "Jian Ayune 01", kelas: "X TKJ 3", created_at: new Date().toISOString() },
  { id: 9, nis: "13700/2350.061", name: "Owalah Yowes 01", kelas: "XI TKJ 1", created_at: new Date().toISOString() },
  { id: 10, nis: "13710/2360.061", name: "Yanto Hay 01", kelas: "XI TKJ 2", created_at: new Date().toISOString() },
];
